---
title: "R Function Cheat Sheet"
subtitle: "for SAS, SPSS, and Stata users"
author: "Katie Labgold, PhD, MPH"
date: "Last updated: `r format(Sys.Date(), '%m/%d/%Y')`"
output:
  html_document:
    theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(dplyr)
library(flextable)
library(htmltools)

# --- EDIT THIS PATH if the xlsx lives somewhere else ---
df <- rio::import("Labgold20206_R_function_cheatsheet_corrected.xlsx")

# Shared styling helper so every table looks the same
style_table <- function(ft, header_color = "#2C3E50") {
  ft %>%
    theme_vanilla() %>%
    bg(part = "header", bg = header_color) %>%
    color(part = "header", color = "white") %>%
    bold(part = "header") %>%
    bold(j = "R Function") %>%
    color(j = "R Function", color = "#276DC2") %>%
    fontsize(size = 10, part = "all") %>%
    padding(padding = 5, part = "all") %>%
    align(align = "left", part = "all") %>%
    valign(valign = "top", part = "body") %>%
    autofit()
}


```

## {.tabset .tabset-pills}

### Full Comparison


```{r}
flextable(df) %>%
  style_table()

```

### SAS Users

```{r}
df %>%
  select(Operation, `R Function`, `R Package`, `SAS Equivalent`) %>%
  flextable() %>%
  style_table(header_color = "#2C3E50")
```

### SPSS Users

```{r}
df %>%
  select(Operation, `R Function`, `R Package`, `SPSS Equivalent`) %>%
  flextable() %>%
  style_table(header_color = "#2C3E50")
```

### Stata Users

```{r}
df %>%
  select(Operation, `R Function`, `R Package`, `Stata Equivalent`) %>%
  flextable() %>%
  style_table(header_color = "#2C3E50")
```
